### ISSUE TITLE
Error:Could not find com.github.Commit451.YouTubeExtractor:youtubeextractor:3.0.0.

### ISSUE THREAD

**Issue by shapon-pal** [Commit451/YouTubeExtractor#12]
I am getting this error when sync Project...
Error:Could not find com.github.Commit451.YouTubeExtractor:youtubeextractor:3.0.0.
I try other version but not working any one.....

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.github.Commit451:YouTubeExtractor: 3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by Jawnnypoo** [comment]
Don't add com.github.Commit451:YouTubeExtractor: 3.0.0 to your classpath, add it as a dependency in your module
