### ISSUE TITLE
which one is correct thumbnail image ? 

### ISSUE THREAD

**Issue by salehmosleh** [Commit451/YouTubeExtractor#13]
here are some image urls that i get from getThumbnails() , and some of them is a html page , not image , how can find a real image ?
```
https://img.youtube.com/vi/rXKwjQkAphw/maxresdefault.jpg
https://img.youtube.com/vi/rXKwjQkAphw/sddefault.jpg
 https://img.youtube.com/vi/rXKwjQkAphw/hqdefault.jpg
https://img.youtube.com/vi/rXKwjQkAphw/mqdefault.jpg
https://img.youtube.com/vi/rXKwjQkAphw/default.jpg
```

**Comment by Jawnnypoo** [comment]
What exactly are you expecting? They are image URLs and you should use a library like Picasso or Glide to load them into an ImageView

**Comment by salehmosleh** [comment]
For example below url does not load :
https://img.youtube.com/vi/rXKwjQkAphw/maxresdefault.jpg
But it loads fine:
https://img.youtube.com/vi/rXKwjQkAphw/mqdefault.jpg
Also, i use mqdefault.jpg image , it can be load fine for some tests,
At the end, thank you so much for your project , i create app and make money by your free plugin.

**Comment by Jawnnypoo** [comment]
Yeah, it just depends on the videos on which ones are valid.
