### ISSUE TITLE
Don't work with some YouTube Id

### ISSUE THREAD

**Issue by Jericho2Code** [Commit451/YouTubeExtractor#2]
Strange behavior, one day it worked with id = 3IE6PBwzXZA, the other day stopped.

**Comment by salehmosleh** [comment]
cannot download some videos , for example below links:
[https://youtu.be/T-YiIjk5WFs](https://youtu.be/T-YiIjk5WFs)
[https://youtu.be/gZElvYWYctg](https://youtu.be/gZElvYWYctg)

**Comment by Jawnnypoo** [comment]
Works on the latest

**Comment by salehmosleh** [comment]
Hi , i tested it on latest version , amd it works fine, thank you
