### ISSUE TITLE
failed to find pattern "(["\'])signature\1\s*,\s*([a-zA-Z0-9$]+)\(

### ISSUE THREAD

**Issue by Vipul12Thawre** [Commit451/YouTubeExtractor#24]
Can you solve this ?,

I am getting this in some videos

failed to find pattern "(["\'])signature\1\s*,\s*([a-zA-Z0-9$]+)\(

**Comment by hannojg** [comment]
Can you give an example of video ids? 
Are you sure the videos you are testing are not age restricted & are available in your country?

**Comment by Vipul12Thawre** [comment]
> Can you give an example of video ids?
> Are you sure the videos you are testing are not age restricted & are available in your country?

Hi @hannojg  after updating your library to latest version that is resolved now , Thanks for your new update , you added the old signature pattern also I think

Thanks Man. 👍
