### ISSUE TITLE
how to extract 4k streaming url from youtube

### ISSUE THREAD

**Issue by zia-limemedia** [Commit451/YouTubeExtractor#25]
I am using this library with java project and i am getting only 5 type of video url ma is only 720p. how to get max or high 4k url from youtube. 
https://www.youtube.com/watch?v=gMaDhkNJA2g
here is sample video. 

Best Zia

**Comment by abdullahmehmood** [comment]
Did you able to play YouTube video in this library? I am also getting 5 type of urls but non of them are working.

**Comment by zia-limemedia** [comment]
yes,i am playing with 720. you need to change the formate for regular expression.
