### ISSUE TITLE
Most of Video cannot be extracted

### ISSUE THREAD

**Issue by JmyW** [Commit451/YouTubeExtractor#29]
I tried some Video but haven't seen a successful extraction ... :-(
Refer the URL below, they are all failed.

https://www.youtube.com/watch?v=Il-an3K9pjg
https://www.youtube.com/watch?v=kHLHSlExFis

**Comment by JmyW** [comment]
I offer more IDs which is failed in my side for your try.

feOq6MWeUXA , l6pFa0qX9Tk , FWtbGkpdoP4 , imksLPHX1ZM

**Comment by naveedhassan913** [comment]
I made a lib for extracting yt videos.. And its working perfectly on any video.
https://github.com/naveedhassan913/YouTubeExtractor

**Comment by naveedhassan913** [comment]
Its working on above videos.

**Comment by mrhussnain** [comment]
@naveedhassan913 but have issue with age restricted videos
