### ISSUE TITLE
Working on some Video ID and not on another

### ISSUE THREAD

**Issue by sushant4anshu** [Commit451/YouTubeExtractor#3]

**Comment by sushant4anshu** [comment]
working FTD9aA4S5BY
Not working nVd8kYMimaM

**Comment by sohel2178** [comment]
I face the same Problem as sushant4anshu describe

**Comment by thiyagurtg** [comment]
I too face the same problem. Later few investigation I found that, Only copyrights video are not working(Eg: All the video which has Copyright by Vevo). All other videos generates download links and its working fine.

**Comment by Jawnnypoo** [comment]
Yeah, if there is DRM on the video, it will not be able to find the streaming links
