### ISSUE TITLE
Failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var lea=function(a){a=a.split("");var b=[function(c,d){d=(d%c.length+c.length)%c.length;c.splice(-d).reverse().forEach(function(e){return c.unshift(e)};"

### ISSUE THREAD

**Issue by Aravindraj93** [Commit451/YouTubeExtractor#36]
implementation 'com.github.Commit451:YouTubeExtractor:5.0.0'

It was working fine. But suddenly it stopped working and gives the error for all the youtube videos :
" failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var lea=function(a){a=a.split("");var b=[function(c,d){d=(d%c.length+c.length)%c.length;c.splice(-d).reverse().forEach(function(e){return c.unshift(e)};" "

**Comment by Jawnnypoo** [comment]
Fixed with 5.0.1
