### ISSUE TITLE
Extracted video Urls sometimes have no sound when played in exoplayer

### ISSUE THREAD

**Issue by marcoRS** [Commit451/YouTubeExtractor#38]
On version 5.0.2 some video urls do not contain sound when played in exoplayer or in chrome browser. 

For example video with `videoId = mVhh0oATqBI`
The youtube video can be found here: https://www.youtube.com/watch?v=mVhh0oATqBI&list with sound.

**Comment by Jawnnypoo** [comment]
This is a pretty complex problem in which sometimes we get back stream URLs that are just audio or just video, and I think the idea is to play them both and keep them in sync. 

I have updated the lib to 6.0.0, which will allow you to determine which type of stream you want. If you just want to deal with video (easiest for exoplayer), you can do something like this:
```
val videoUrl = result.streams
            .filterIsInstance<Stream.VideoStream>()
            .max()
            ?.url
```

**Comment by Aravindraj93** [comment]
val videoUrl = result.streams
            .filterIsInstance<Stream.VideoStream>()
            .max()
            ?.url

this bit of code only gives the video url. The video plays without audio. How do I fix it.
