### ISSUE TITLE
How to implement this library in java

### ISSUE THREAD

**Issue by Aravindraj93** [Commit451/YouTubeExtractor#39]
Hi, 
    How do I call this method "val videoUrl = result.streams
            .filterIsInstance<Stream.VideoStream>()
            .max()
            ?.url" 

in java.

**Comment by Jawnnypoo** [comment]
Probably something like this:
```
List<Stream.VideoStream> videoStreams = new ArrayList()
for (Stream stream in result.streams) {
   if (stream instanceOf Stream.VideoStream) {
       videoStreams.add(stream)
   }
}
Collections.sort(videoStreams)
String url = videoStreams[0].url
```

**Comment by Aravindraj93** [comment]
Thank you for helping me. But It doesn't work.  I will try what can I do.
