### ISSUE TITLE
com.commit451.youtubeextractor.YouTubeExtractionException: Status: fail     Reason: Invalid parameters.     Error code: 2

### ISSUE THREAD

**Issue by craftbox2245** [Commit451/YouTubeExtractor#40]
I am using below code in my project 
but i am gettin error like 

Error: 
com.commit451.youtubeextractor.YouTubeExtractionException: Status: fail
    Reason: Invalid parameters.
    Error code: 2

Code: 
// You probably would want to keep one of these extractors around.
YouTubeExtractor extractor = YouTubeExtractor.create();
mExtractor.extract("9d8wWcJLnFI").enqueue(new Callback<YouTubeExtractionResult>() {
    @Override
    public void onResponse(Call<YouTubeExtractionResult> call, Response<YouTubeExtractionResult> response) {
        Uri hdUri = result.getHd1080VideoUri();
        //See the sample for more
    }

    @Override
    public void onFailure(Call<YouTubeExtractionResult> call, Throwable t) {
        t.printStackTrace();
        //Alert your user!
    }
});

please help me @Commit 451

**Comment by Jawnnypoo** [comment]
You are using a super old version of the library. You need to update to the newest version (6.0.0) for it to work.
