### ISSUE TITLE
All Videos playing without audio.

### ISSUE THREAD

**Issue by Aravindraj93** [Commit451/YouTubeExtractor#41]
implementation 'com.github.Commit451:YouTubeExtractor:6.0.0'

val videoUrl = result.streams
.filterIsInstance<Stream.VideoStream>()
.max()
?.url"

All Videos playing without audio.
How do I fix it.

**Comment by Aravindraj93** [comment]
Try something like this to get the stream urls with Video and Audio

     `private var MyVodList: ArrayList<Stream.VideoStream> = ArrayList()`


    `for (item in extraction.streams){
                        if (item is Stream.VideoStream) {
                            MyVodList.add(item)
                        }

                    }
                    Collections.sort(MyVodList)
                    for (item in MyVodList){
                        if (!item.isVideoOnly){
                            Log.e("Audio&Vid", item.url)
                            videoUrl = item.url
                        }
                    }`

**Comment by Jawnnypoo** [comment]
Yep, good solution.
