### ISSUE TITLE
getting response body null

### ISSUE THREAD

**Issue by habibmhamadi** [Commit451/YouTubeExtractor#44]
I am using version 2.1.0 and i get response body null.
this is my code:
![Capture](https://user-images.githubusercontent.com/34987353/80299081-e71d4f00-87a6-11ea-837f-23de2b7ee7a9.PNG)

**Comment by Jawnnypoo** [comment]
You cannot use the old version. Google changes the YouTube page payload all the time and this library has to be updated each time it changes.

**Comment by habibmhamadi** [comment]
But i can't use newer version than this.
What is the latest version?

**Comment by Jawnnypoo** [comment]
6.0.0. You'll have to make code changes, but the README should be able to get you up to speed.

**Comment by habibmhamadi** [comment]
Thanks and does it have 720p or 1080p video with no muted audio

**Comment by Jawnnypoo** [comment]
It depends on the video

**Comment by habibmhamadi** [comment]
Bcz i used another lib and videos larger than 640p are muted.

**Comment by Jawnnypoo** [comment]
Yeah, there is a good chance you might have to use the video URL and the audio URL combined to get the results you want.

**Comment by habibmhamadi** [comment]
How can i do that plz
I tried to download video and audio separately and then merge them using mp4parser but the lib had an issue and couldn't do that.

**Comment by Jawnnypoo** [comment]
There is likely a way to use ExoPlayer to stream both in sync with one another https://github.com/google/ExoPlayer

**Comment by habibmhamadi** [comment]
Thank you 🙏💕

**Comment by Jawnnypoo** [comment]
No problem! Good luck! You could also look into https://github.com/PierfrancescoSoffritti/android-youtube-player if you wanted everything to be handled.
