### ISSUE TITLE
how to get name of video

### ISSUE THREAD

**Issue by salehmosleh** [Commit451/YouTubeExtractor#5]
how can i get a name of video for save it ?! can i get title of video ?

**Comment by thiyagurtg** [comment]
I found an alternative solution for this.. Parse your youtube link and it will return the Title of the video.

public static String getTitleQuietly(String youtubeUrl) {
        try {

//Runtime permission if you don't need remove these lines
            if (android.os.Build.VERSION.SDK_INT > 9)
            {
                StrictMode.ThreadPolicy policy =
                        new StrictMode.ThreadPolicy.Builder().permitAll().build();
                StrictMode.setThreadPolicy(policy);
            }
            if (youtubeUrl != null) {
                URL embededURL = new URL("http://www.youtube.com/oembed?url=" +
                        youtubeUrl + "&format=json"
                );

                return new JSONObject(IOUtils.toString(embededURL)).getString("title");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

**Comment by Jawnnypoo** [comment]
Thanks for the alternative solution. But please, do not change the thread policy and do this on the main thread. Use something like OkHttp or Retrofit instead, and do the work on a background thread
