### ISSUE TITLE
java.lang.Exception: failed to find pattern

### ISSUE THREAD

**Issue by LiuDongCai** [Commit451/YouTubeExtractor#52]
java.lang.Exception: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var iea=function(a){a=a.split("");var b=[-1215677809,null,-1744521562,833462946,694270393,function(c,d){d=(d%c.length+c.length)%c.length;c.splice(d,1)};"

implementation 'com.github.Commit451:YouTubeExtractor:6.0.0'

**Comment by MinhToanIT** [comment]
the same issue, could you please fix this issue ASAP. Thank you!

**Comment by MohitSharma1210** [comment]
I am facing the same issue. Can you fix ASAP.

**Comment by Jordenmax** [comment]
Same Issue, please fix it asap, None of the youtube video is playing

**Comment by Jawnnypoo** [comment]
Can you give an example of a video ID that causes this?

**Comment by LiuDongCai** [comment]
> Can you give an example of a video ID that causes this?

https://www.youtube.com/watch?v=HbJr03hTfWg

**Comment by MohitSharma1210** [comment]
9d8wWcJLnFI

**Comment by Jawnnypoo** [comment]
It works on 6.0.1

**Comment by Jawnnypoo** [comment]
You likely need to change to the latest version of this library and you will see the errors go away.
