### ISSUE TITLE
Link expiration

### ISSUE THREAD

**Issue by aliakkawi** [Commit451/YouTubeExtractor#6]
Hello, 
iam using YoutubeExtractor to create a playlist that plays in the background using "service", the problem is after couple of hours it seems that the rtsp links expire, and they are not playing anymore. 
Please advice me how to fix the issue.
Thanks.

**Comment by Jawnnypoo** [comment]
Hey there, cannot really help you there. I am not familiar with the way RTSP links work on the YouTube side of things. Best bet I suppose would be to store the YouTube video ID, and refetch the RTSP link using this extractor when it is needed. Maybe take a look into how it is handled in https://github.com/TeamNewPipe/NewPipe to get some ideas going?
