### ISSUE TITLE
Not getting 1080p video url

### ISSUE THREAD

**Issue by AnandSaran** [Commit451/YouTubeExtractor#7]
Hi returning null for 1080p video

**Comment by Jawnnypoo** [comment]
Can you provide the video ID?

**Comment by AnandSaran** [comment]
xNv6m913rTs this is video id.

**Comment by AnandSaran** [comment]
and "Y3-PeuQ7nvY" for this id i didn't get any url.
Please help me out

**Comment by Jawnnypoo** [comment]
Not all videos have 1080p stream urls
